# Generated by Django 3.1.1 on 2021-01-09 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_request_dish_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mobile',
            field=models.CharField(default=django.utils.timezone.now, max_length=13),
            preserve_default=False,
        ),
    ]
